<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierAddress" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Supplier_Product" Member="Products" ThisKey="SupplierId" OtherKey="SupplierId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Shops" Member="Shops">
    <Type Name="Shop">
      <Column Name="ShopId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShopName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ShopAddress" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Shop_Order" Member="Orders" ThisKey="ShopId" OtherKey="ShopId" Type="Order" />
      <Association Name="Shop_Event" Member="Events" ThisKey="ShopId" OtherKey="ShopId" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ProductDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProductPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Product_Order" Member="Orders" ThisKey="ProductId" OtherKey="ProductId" Type="Order" />
      <Association Name="Supplier_Product" Member="Supplier" ThisKey="SupplierId" OtherKey="SupplierId" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderStatus" Member="OrderStatus">
    <Type Name="OrderStatus">
      <Column Name="OrderStatusId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderStatus" Member="Order" ThisKey="OrderId" OtherKey="OrderId" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShopId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Order_OrderStatus" Member="OrderStatus" ThisKey="OrderId" OtherKey="OrderId" Type="OrderStatus" />
      <Association Name="Order_Event" Member="Events" ThisKey="OrderId" OtherKey="OrderId" Type="Event" />
      <Association Name="Product_Order" Member="Product" ThisKey="ProductId" OtherKey="ProductId" Type="Product" IsForeignKey="true" />
      <Association Name="Shop_Order" Member="Shop" ThisKey="ShopId" OtherKey="ShopId" Type="Shop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="EventId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShopId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Order_Event" Member="Order" ThisKey="OrderId" OtherKey="OrderId" Type="Order" IsForeignKey="true" />
      <Association Name="Shop_Event" Member="Shop" ThisKey="ShopId" OtherKey="ShopId" Type="Shop" IsForeignKey="true" />
    </Type>
  </Table>
</Database>